### PR TITLE
Commits added to the pr

### PR DESCRIPTION
**Pull request by carmelo12341**
Add the .install, changed pkgrel, and updated srcinfo

### CODE REVIEW

**Comment by carmelo12341** [comment]
Using this package, the app gives me no problems, and everything is working fine. Except for that "Window is ready" notification in gnome, I've been trying to fix that but nothing is working.
I also made other minor changes to the code.

**Comment by MarcinWieczorek** [comment]
Yeah "Window is ready" thing drives me crazy...
I'll test it out and accept

**Comment by MarcinWieczorek** [comment]
I wonder if .install size has to be added to sources.

**Comment by MarcinWieczorek** [comment]
And you need to add it to the PKGBUILD.

**Comment by carmelo12341** [comment]
nope, looking at other packages, I could say is not needed.

**Comment by MarcinWieczorek** [comment]
Your branch does not work at all. I'm closing this.

**Comment by carmelo12341** [comment]
huh, I am using this right now, It is working for me :/

**Comment by MarcinWieczorek** [comment]
There are syntax errors in .install file. Thanks for your help, I'm using your PR to make it on my own now (and test some cool things)

**Comment by carmelo12341** [comment]
the .install file is actually the same from the other messengerfordesktop package, the one from aluxian :/

**Comment by MarcinWieczorek** [comment]
It is not.
https://aur.archlinux.org/cgit/aur.git/tree/messengerfordesktop.install?h=messengerfordesktop
14 & 18

**Comment by carmelo12341** [comment]
I changed that line because the .desktop file is installed in the PKGBUILD, eveything else is the same

**Comment by MarcinWieczorek** [comment]
Send me your name and email (here or marcin@marcin.co) if you want to be added as a contributor to the PKGBUILD.

**Comment by carmelo12341** [comment]
Carlos Toro
ertsheiker@gmail.com
c:

**Pull request closed without merging**
